spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-dev
    
config:
  info: "master branch,sneakerhead0410/microservicecloud-config-client.yml version = 6"
---
spring:
  profiles: test   #测试环境
  application: 
    name: microservicecloud-config-test
    
config:
  info: "master branch,sneakerhead0410/microservicecloud-config-client.yml version = 6"
#  请保存为UTF-8格式
