spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: config-client
    
config:
  info: "master branch,sneakerhead0410/microservicecloud-config-client.yml version = 7"
---
spring:
  profiles: test   #测试环境
  application: 
    name: config-client
    
config:
  info: "master branch,sneakerhead0410/microservicecloud-config-client.yml version = 7"
#  请保存为UTF-8格式
